### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by hut8** [TheBosZ/geocoder-service#1]
Does this really need `~1.2.23` (https://github.com/TheBosZ/geocoder-service/blob/master/bower.json#L6) ? Can it use something later? I'm trying this on a project but a lot of my other dependencies need a more recent version of Angular, so right now this won't load.

**Comment by TheBosZ** [comment]
I just pushed a new v0.0.6 version to bump the requirements. I haven't tested this library against newer Angular yet, but it should work just fine.
